---
title: "World Happiness"
author: 
  - Nazirov Tural[^1]
bibliography: ../bibliography/biblio.bib
csl: ../csl/apa.csl
header-includes:
  - \usepackage{polyglossia}
  - \setmainlanguage{english}
  - \usepackage{booktabs}
  - \usepackage{caption} 
  - \captionsetup[table]{skip=10pt}
output:
  bookdown::pdf_document2:
    fig_caption: yes
    fig_height: 3
    fig_width: 4
    keep_tex: no
    latex_engine: xelatex
    number_sections: yes
    toc: no
geometry: margin=1in
link-citations: yes
urlcolor: blue
fontsize: 12pt
biblio-style: apalike
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = FALSE, echo = TRUE, message = FALSE, warning = FALSE)
```

<!-- ======================================================================= -->
<!-- ============================== FOOTNOTES ============================== -->
<!-- ======================================================================= -->
[^1]: 20080163, [Github Repo](https://github.com/Turalnzv/Midterm)


# Introduction

The World Happiness Report is an annual publication produced by the United Nations Sustainable Development Solutions Network, which ranks countries based on the level of happiness of their citizens. The World Happiness Report uses a variety of factors, including economic, social, and health-related indicators, to calculate a score for each country, which is then used to rank them. The report is based on data collected from a range of sources, including surveys of people in each country, and it provides valuable insights into the factors that contribute to happiness and well-being across the world. The World Happiness Report has become an important resource for policymakers, researchers, and the general public, as it helps to inform policies and initiatives aimed at improving the lives of people around the world.

## Literature Review

The paper "The Origins of Happiness: The Science of Well-Being over the Life Course" @jones2018clark by Andrew Clark and colleagues provides a comprehensive review of the research on the determinants of happiness over the life course. They suggest that factors such as social relationships, health, and meaningful work are key determinants of happiness, and that these factors may be particularly important during certain stages of the life course.
The paper "Happiness and Environmental Sustainability: A Review of the Literature" @steinberger2022happiness by Julia Steinberger and colleagues examined the relationship between happiness and environmental sustainability. They found that sustainable practices such as reducing consumption, promoting renewable energy, and protecting biodiversity can lead to greater levels of happiness and well-being over the long-term. They suggest that policies aimed at promoting sustainability could have significant benefits for both the environment and human well-being.
The study "Income and Well-Being: An Empirical Analysis of the Comparison Income Effect" @easterlin2013income by Richard Easterlin and Onnicha Sawangfa found that individuals' happiness is influenced not only by their own income, but also by the income of others in their reference group. They suggest that policies aimed at reducing income inequality could have significant benefits for overall levels of happiness.
The study "Happiness, Culture, and Context" @oishi2019happiness by Shigehiro Oishi and Selin Kesebir examined the role of culture and context in shaping individuals' experiences of happiness. They found that cultural factors such as individualism and collectivism, as well as situational factors such as the presence of social support, were important predictors of happiness. They suggest that policies aimed at promoting cultural and situational factors that support happiness could have significant benefits for overall levels of well-being.
The study "Happiness and Productivity" @de2020happiness by Jan-Emmanuel De Neve and colleagues found that happier workers are more productive, suggesting that policies aimed at promoting workplace happiness could have significant economic benefits. They suggest that employers can promote happiness among workers through measures such as flexible working arrangements, social activities, and opportunities for personal development.
The paper "Sustainable Happiness: Lessons from the World's Happiest People and Places" @o2019sustainable by Catherine O'Brien and Robert J. Vallerand examines the relationship between sustainability and happiness. They suggest that promoting sustainable practices such as environmental conservation, social justice, and economic stability can lead to greater levels of happiness and well-being over the long-term.

\newpage
# References {#references}
<div id="refs"></div>

